[colors]
table_header_color = "#000000"
all_cpu_color = "#e6af00"
avg_cpu_color = "#ba0000"
cpu_core_colors = ["#ff3f00", "#e6af00", "#00ba00", "#0072ff", "#ba00ba", "#00baba", "#bababa", "#ba0000"]
ram_color = "#0072ff"
swap_color = "#ba00ba"
arc_color = "#ba00ba"
gpu_core_colors = ["#ff3f00", "#e6af00", "#00ba00", "#0072ff"]
temp_color = "#ff3f00"
disk_color = "#00ba00"
rx_color = "#00baba"
tx_color = "#ba0000"
rx_total_color = "#00baba"
tx_total_color = "#ba0000"
border_color = "#555555"
highlighted_border_color = "#e6af00"
disabled_text_color = "#555555"
text_color = "#000000"
graph_color = "#bababa"
cursor_color = "#cfa160"
selected_text_color = "#000000"
selected_bg_color = "#edd5b5"
high_battery_color = "#00ba00"
medium_battery_color = "#e6af00"
low_battery_color = "#ff3f00"
