separator = " "
separator_color = "#C7522A" # Red-Orange (Dune)
key_color = "#E9B489"     # Sand
prefer_small_ascii = true

[box]
title = " kaian0n "
border = "single"
visible = true

[bar]
glyph = "▮ "
hide_delimiters = true
visible = true

[randomize]
key_color = false
separator_color = false

[custom_ascii]
color = "#E9B489"         # Sand
path = "~/.config/macchina/themes/Luffytaro.txt"

[keys]
host = "kaian0n"
kernel = "XNU"
packages = " Packages"
terminal = " Terminal"
shell = " Shell"
cpu = " CPU"
cpu_load = " CPU Load"
memory = "󰍛 Memory"
battery = " Battery"
uptime = " Uptime"
resolution = "󱡶 Resolution"
[interface]



