[Interface]
PrivateKey = +OApYQMjRhi0cQKDVRYZ9qY9HLzmO7jYYDLNK1QDxWo=
Address = 10.100.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = UYxGGEBSCJUoFnK6fq8WucX+sqaLmUndW/pXh6clowE=
Endpoint = 174.27.160.227:51820
AllowedIPs = 10.100.0.0/24
PersistentKeepalive = 25
